---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# periodization

This package is currently under development. Functions to calculate the ACWR of several individuals (or just one individual) have been implemented.

## ACWR calculation example

First, we have to load the data which consists in a database with the following columns: 
- ID: subject identifier (integer). 
- TL: training load (sRPE - integer). 
- weeks: week of training (integer).
- training_dates: date of the training (date format in excel - 7/1/22).

``` r
# Read dataframe (excel)
training_data <- readxl::read_xlsx("training_data.xlsx")

# check column names
# names(training_data)
# "ID"  "TL"  "Week" "Training_Dates"

# Calculate ACWR for every ID using the three available methods
res_ACWR <- (df = training_data,
             ID = "ID",
             TL = "TL",
             weeks = "Week",
             training_dates = "Training_Dates",
             ACWR_method = c("EWMA", "RAC", "RAU"))
```

The ACWR function returns the training data dataframe plus the acute, 
chronic and ACWR for each method. In the previous example nine columns have been added
to the dataframe (EWMA_acute, EWMA_chronic, EWMA_ACWR, RAC_acute, RAC_chronic, RAC_ACWR,
RAU_acute, RAU_chronic and RAU_ACWR).


## EWMA, RAC and RAU functions

EWMA, RAC and RAU functions could be used for each subjects individually.

``` r
# Get the data of the first participant
participant_1 <- training_data[ training_data[["ID"]] == 1,  ]

res_EWMA <- EWMA(TL = participant_1$TL)

res_RAC <- RAC(TL = participant_1$TL ,
              weeks = participant_1$Week,
              training_dates = participant_1$Training_Dates)
              
res_RAU <- RAU(TL = participant_1$TL ,
              weeks = participant_1$Week,
              training_dates = participant_1$Training_Dates)
```

Each function returns a list with the acute, chronic and ACWR.             

